# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: 'Angular PR Build'
trigger:
- master

pool:
  vmImage: 'Ubuntu-18.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.18.x'
  displayName: 'Install Node.js'

- task: npmAuthenticate@0
  inputs:
    workingFile: './AngularApp/.npmrc'
  displayName: 'NPM Authenticate'

- script: |
    cd AngularApp
    npm install -g @angular/cli@8.0.2
    npm install
    npm run build
  displayName: 'npm install and build'
